---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeops
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - kubeops.net
    secretName: kube-lego-account
  backend:
    serviceName: ghost
    servicePort: 80
  rules:
  - host: kubeops.net
    http:
      paths:
      - path: /*
        backend:
          serviceName: ghost
          servicePort: 80