apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-configmap
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"
    [admin]
      port = 8083

