---
apiVersion: v1
metadata:
  name: kube-lego
  namespace: default
data:
  # modify this to specify your address
  lego.email: "josep.pla@gmail.com"
  # configre letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap