apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    component: influxdb
spec:
  type: NodePort
  selector:
    component: influxdb
  ports:
  - name: http
    port: 8083
    protocol: TCP
    nodePort: 30083
  - name: admin-ui
    port: 8086
    protocol: TCP
    nodePort: 30086
---
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: influxdb
spec:
  serviceName: influxdb
  replicas: 1
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.1.1-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
          name: http
        - containerPort: 8083 
          name: admin_ui
        resources:
          limits:
            cpu: "1024m"
            memory: 2Gi
          requests:
           cpu: "500m"
           memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: influxdb-data
          mountPath: /influxdb_data
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: influxdb-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: HostPath
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi