---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  ports:
  - nodePort: 30000
    name: ghost
    targetPort: 2368
  selector:
    app: ghost
  type: NodePort         
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ghost
spec:
  serviceName: "ghost"
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ghost
        image: ghost:0.11.7
        ports:
        - containerPort: 2368
          name: ghost
        volumeMounts:
        - name: ghostdata
          mountPath: /var/lib/ghost
  volumeClaimTemplates:
  - metadata:
      name: ghostdata
      annotations:
          volume.alpha.kubernetes.io/storage-class: pd-standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
