apiVersion: v1
kind: Service
metadata:
  labels:
    run: ghost
  name: ghost
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 2368
  selector:
    run: ghost
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: ghost
  name: ghost
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ghost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ghost
    spec:
      containers:
      - image: ghost:0.11.7
        imagePullPolicy: IfNotPresent
        name: ghost
        ports:
        - containerPort: 2368
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

